name: Test conditional parameter
on: 
  release:
    types: [released]
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF##*/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/Dockerfile
          push: true # ${{ github.event_name == 'release' }}
          tags: |
            ghcr.io/yuri05/test_3:v4.2.2
            ghcr.io/yuri05/test_3:latest
#           ghcr.io/yuri05/test_3:${{ steps.tag_name.outputs.SOURCE_TAG}}
